kind: Deployment
apiVersion: apps/v1
metadata:
  name: image-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: image-test
    spec:
      containers:
        - name: image-test
          image: 'openshift/hello-openshift'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: test
      serviceAccount: test
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
