---
- name: Installation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Install collections
      ansible.builtin.command: ansible-galaxy collection install -r collections/requirements.yaml --force
      register: install_collections
      changed_when: install_collections.rc == 0

    - name: Create Demo namespaces
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ namespaces }}"
      loop_control:
        loop_var: namespace

    - name: Configure Bitwarden
      ansible.builtin.include_role:
        name: demos.utils.bitwarden
      vars:
        bitwarden_operation: install

    - name: Configure Gitea
      ansible.builtin.include_role:
        name: demos.utils.gitea

    - name: Configure ArgoCD
      ansible.builtin.include_role:
        name: demos.utils.argocd

    - name: Create demo applications
      ansible.builtin.command:
        cmd: oc apply -f app-set.yaml

  vars_files:
    - vars.yaml
