---
- name: Uninstallation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Remove Bitwarden
      ansible.builtin.include_role:
        name: demos.utils.bitwarden
      vars:
        bitwarden_operation: uninstall

    - name: Delete Demo namespaces
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ namespaces }}"
      loop_control:
        loop_var: namespace

  vars_files:
    - vars.yaml
