kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
  selector:
    app: backend
    deployment: backend