apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret
spec:
  organizationId: "cd864c42-0667-4521-afb0-aae600ef844c"
  secretName: database-credentials
  map:
    - bwSecretId: 2b4cf82d-7bb4-4f90-a391-b275008566eb
      secretKeyName: username
    - bwSecretId: 371a1632-c42e-4d01-85c8-b28800d967d0
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token