kind: Service
apiVersion: v1
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
  selector:
    app: database
    deployment: database