FROM registry.access.redhat.com/ubi8/python-312

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app.py .

USER 1001
EXPOSE 5000

ENTRYPOINT ["python"]

CMD ["app.py"]